import 'package:hive/hive.dart';

part 'journal_model.g.dart'; // This will be generated by Hive

@HiveType(typeId: 3) // Use a new typeId that doesn't conflict
class JournalEntry extends HiveObject {
  @HiveField(0)
  String text;

  @HiveField(1)
  DateTime date;

  JournalEntry({required this.text, required this.date});
}
